/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedInviteRouteImport } from './routes/_authed.invite'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed.dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedDashboardPropertyIdRouteImport } from './routes/_authed.dashboard/$propertyId'
import { Route as AuthedDashboardPropertyIdIndexRouteImport } from './routes/_authed.dashboard/$propertyId/index'
import { Route as AuthedDashboardPropertyIdInviteRouteImport } from './routes/_authed.dashboard/$propertyId/invite'
import { Route as AuthedDashboardPropertyIdFloorplanEditRouteImport } from './routes/_authed.dashboard/$propertyId/floorplan.edit'
import { Route as AuthedDashboardPropertyIdRoomRoomIdIndexRouteImport } from './routes/_authed.dashboard/$propertyId/room.$roomId/index'
import { Route as AuthedDashboardPropertyIdRoomRoomIdNewRouteImport } from './routes/_authed.dashboard/$propertyId/room.$roomId/new'
import { Route as AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRouteImport } from './routes/_authed.dashboard/$propertyId/room.$roomId/edit.$choreId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInviteRoute = AuthedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardPropertyIdRoute =
  AuthedDashboardPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPropertyIdIndexRoute =
  AuthedDashboardPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)
const AuthedDashboardPropertyIdInviteRoute =
  AuthedDashboardPropertyIdInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)
const AuthedDashboardPropertyIdFloorplanEditRoute =
  AuthedDashboardPropertyIdFloorplanEditRouteImport.update({
    id: '/floorplan/edit',
    path: '/floorplan/edit',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)
const AuthedDashboardPropertyIdRoomRoomIdIndexRoute =
  AuthedDashboardPropertyIdRoomRoomIdIndexRouteImport.update({
    id: '/room/$roomId/',
    path: '/room/$roomId/',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)
const AuthedDashboardPropertyIdRoomRoomIdNewRoute =
  AuthedDashboardPropertyIdRoomRoomIdNewRouteImport.update({
    id: '/room/$roomId/new',
    path: '/room/$roomId/new',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)
const AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute =
  AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRouteImport.update({
    id: '/room/$roomId/edit/$choreId',
    path: '/room/$roomId/edit/$choreId',
    getParentRoute: () => AuthedDashboardPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/invite': typeof AuthedInviteRoute
  '/dashboard/$propertyId': typeof AuthedDashboardPropertyIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/$propertyId/invite': typeof AuthedDashboardPropertyIdInviteRoute
  '/dashboard/$propertyId/': typeof AuthedDashboardPropertyIdIndexRoute
  '/dashboard/$propertyId/floorplan/edit': typeof AuthedDashboardPropertyIdFloorplanEditRoute
  '/dashboard/$propertyId/room/$roomId/new': typeof AuthedDashboardPropertyIdRoomRoomIdNewRoute
  '/dashboard/$propertyId/room/$roomId': typeof AuthedDashboardPropertyIdRoomRoomIdIndexRoute
  '/dashboard/$propertyId/room/$roomId/edit/$choreId': typeof AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/invite': typeof AuthedInviteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/$propertyId/invite': typeof AuthedDashboardPropertyIdInviteRoute
  '/dashboard/$propertyId': typeof AuthedDashboardPropertyIdIndexRoute
  '/dashboard/$propertyId/floorplan/edit': typeof AuthedDashboardPropertyIdFloorplanEditRoute
  '/dashboard/$propertyId/room/$roomId/new': typeof AuthedDashboardPropertyIdRoomRoomIdNewRoute
  '/dashboard/$propertyId/room/$roomId': typeof AuthedDashboardPropertyIdRoomRoomIdIndexRoute
  '/dashboard/$propertyId/room/$roomId/edit/$choreId': typeof AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/invite': typeof AuthedInviteRoute
  '/_authed/dashboard/$propertyId': typeof AuthedDashboardPropertyIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/$propertyId/invite': typeof AuthedDashboardPropertyIdInviteRoute
  '/_authed/dashboard/$propertyId/': typeof AuthedDashboardPropertyIdIndexRoute
  '/_authed/dashboard/$propertyId/floorplan/edit': typeof AuthedDashboardPropertyIdFloorplanEditRoute
  '/_authed/dashboard/$propertyId/room/$roomId/new': typeof AuthedDashboardPropertyIdRoomRoomIdNewRoute
  '/_authed/dashboard/$propertyId/room/$roomId/': typeof AuthedDashboardPropertyIdRoomRoomIdIndexRoute
  '/_authed/dashboard/$propertyId/room/$roomId/edit/$choreId': typeof AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/dashboard'
    | '/invite'
    | '/dashboard/$propertyId'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/$propertyId/invite'
    | '/dashboard/$propertyId/'
    | '/dashboard/$propertyId/floorplan/edit'
    | '/dashboard/$propertyId/room/$roomId/new'
    | '/dashboard/$propertyId/room/$roomId'
    | '/dashboard/$propertyId/room/$roomId/edit/$choreId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/invite'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/$propertyId/invite'
    | '/dashboard/$propertyId'
    | '/dashboard/$propertyId/floorplan/edit'
    | '/dashboard/$propertyId/room/$roomId/new'
    | '/dashboard/$propertyId/room/$roomId'
    | '/dashboard/$propertyId/room/$roomId/edit/$choreId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/_authed/dashboard'
    | '/_authed/invite'
    | '/_authed/dashboard/$propertyId'
    | '/api/auth/$'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/$propertyId/invite'
    | '/_authed/dashboard/$propertyId/'
    | '/_authed/dashboard/$propertyId/floorplan/edit'
    | '/_authed/dashboard/$propertyId/room/$roomId/new'
    | '/_authed/dashboard/$propertyId/room/$roomId/'
    | '/_authed/dashboard/$propertyId/room/$roomId/edit/$choreId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyRoute: typeof VerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/invite': {
      id: '/_authed/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthedInviteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/$propertyId': {
      id: '/_authed/dashboard/$propertyId'
      path: '/$propertyId'
      fullPath: '/dashboard/$propertyId'
      preLoaderRoute: typeof AuthedDashboardPropertyIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/$propertyId/': {
      id: '/_authed/dashboard/$propertyId/'
      path: '/'
      fullPath: '/dashboard/$propertyId/'
      preLoaderRoute: typeof AuthedDashboardPropertyIdIndexRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
    '/_authed/dashboard/$propertyId/invite': {
      id: '/_authed/dashboard/$propertyId/invite'
      path: '/invite'
      fullPath: '/dashboard/$propertyId/invite'
      preLoaderRoute: typeof AuthedDashboardPropertyIdInviteRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
    '/_authed/dashboard/$propertyId/floorplan/edit': {
      id: '/_authed/dashboard/$propertyId/floorplan/edit'
      path: '/floorplan/edit'
      fullPath: '/dashboard/$propertyId/floorplan/edit'
      preLoaderRoute: typeof AuthedDashboardPropertyIdFloorplanEditRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
    '/_authed/dashboard/$propertyId/room/$roomId/': {
      id: '/_authed/dashboard/$propertyId/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/dashboard/$propertyId/room/$roomId'
      preLoaderRoute: typeof AuthedDashboardPropertyIdRoomRoomIdIndexRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
    '/_authed/dashboard/$propertyId/room/$roomId/new': {
      id: '/_authed/dashboard/$propertyId/room/$roomId/new'
      path: '/room/$roomId/new'
      fullPath: '/dashboard/$propertyId/room/$roomId/new'
      preLoaderRoute: typeof AuthedDashboardPropertyIdRoomRoomIdNewRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
    '/_authed/dashboard/$propertyId/room/$roomId/edit/$choreId': {
      id: '/_authed/dashboard/$propertyId/room/$roomId/edit/$choreId'
      path: '/room/$roomId/edit/$choreId'
      fullPath: '/dashboard/$propertyId/room/$roomId/edit/$choreId'
      preLoaderRoute: typeof AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRouteImport
      parentRoute: typeof AuthedDashboardPropertyIdRoute
    }
  }
}

interface AuthedDashboardPropertyIdRouteChildren {
  AuthedDashboardPropertyIdInviteRoute: typeof AuthedDashboardPropertyIdInviteRoute
  AuthedDashboardPropertyIdIndexRoute: typeof AuthedDashboardPropertyIdIndexRoute
  AuthedDashboardPropertyIdFloorplanEditRoute: typeof AuthedDashboardPropertyIdFloorplanEditRoute
  AuthedDashboardPropertyIdRoomRoomIdNewRoute: typeof AuthedDashboardPropertyIdRoomRoomIdNewRoute
  AuthedDashboardPropertyIdRoomRoomIdIndexRoute: typeof AuthedDashboardPropertyIdRoomRoomIdIndexRoute
  AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute: typeof AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute
}

const AuthedDashboardPropertyIdRouteChildren: AuthedDashboardPropertyIdRouteChildren =
  {
    AuthedDashboardPropertyIdInviteRoute: AuthedDashboardPropertyIdInviteRoute,
    AuthedDashboardPropertyIdIndexRoute: AuthedDashboardPropertyIdIndexRoute,
    AuthedDashboardPropertyIdFloorplanEditRoute:
      AuthedDashboardPropertyIdFloorplanEditRoute,
    AuthedDashboardPropertyIdRoomRoomIdNewRoute:
      AuthedDashboardPropertyIdRoomRoomIdNewRoute,
    AuthedDashboardPropertyIdRoomRoomIdIndexRoute:
      AuthedDashboardPropertyIdRoomRoomIdIndexRoute,
    AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute:
      AuthedDashboardPropertyIdRoomRoomIdEditChoreIdRoute,
  }

const AuthedDashboardPropertyIdRouteWithChildren =
  AuthedDashboardPropertyIdRoute._addFileChildren(
    AuthedDashboardPropertyIdRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardPropertyIdRoute: typeof AuthedDashboardPropertyIdRouteWithChildren
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardPropertyIdRoute: AuthedDashboardPropertyIdRouteWithChildren,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedInviteRoute: typeof AuthedInviteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedInviteRoute: AuthedInviteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyRoute: VerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
